### ISSUE TITLE
Add information about network multipliers and rental fees

### ISSUE THREAD

**Issue by dgarcia360** [nemfoundation/symbol-explorer#267]
Since catapult fees vary over time, the explorer should highlight the following information over the period of `maxDifficultyBlocks` to be able to determine how much it cost to register namespaces, mosaics and send transactions.

* averageFeeMultiplier
* medianFeeMultiplier
* highestFeeMultiplier 
* lowestFeeMultiplier
* effectiveRootNamespaceRentalFeePerBlock
* effectiveChildNamespaceRentalFee
* effectiveMosaicRentalFee

More info: 
* https://nemtech.github.io/concepts/fees.html
* https://github.com/nemtech/catapult-rest/issues/98

Inspiration:
* https://ethgasstation.info/

**Comment by decentraliser** [comment]
for reference here is the network fee implementation in the browser wallet
https://github.com/nemfoundation/nem2-desktop-wallet/blob/master/src/core/model/NetworkProperties.ts#L83-L112

**Comment by AnthonyLaw** [comment]
will continue this issue after https://github.com/nemtech/catapult-rest/issues/254 is complete
