### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by AnthonyLaw** [nemfoundation/symbol-explorer#307]
- Font-family : `Noto Sans`
- Logo: `Symbol from NEM`
- Icon: `Connector`
- Brand Color:  [Color Pallete](https://lh4.googleusercontent.com/W1eK8roT8g27nB-S6NJpgnZWxJxMop_zMphMnyuVOffd2F3Lcrk5cbTpPVIbpkWmNXiD1aeqlm27VM6VChILmGEMkNywh9eZUmvKXEqpaA73G_8f4u3RDUWqKzqKhJ0g1bp3xdM)

**Comment by AnthonyLaw** [comment]
while waiting `XYM`, should we take off the XEM price chart and infomation in Symbol Explorer?
@evias @jabo38

**Comment by dgarcia360** [comment]
| Task                                                         |Status| Responsible  |
|--------------------------------------------|------|----------------|
| Rebranding branch created                    |        |contributors    |
| New design applied (font, logos, colors)|        |contributors    |
| Codename references renamed             |         |contributors   |
| Ticker references renamed                     |         |contributors   |
| Links reviewed                                        |         |contributors   |
| README reviewed                                  |         |sig-docs         |
| PR created                                              |         |contributors   |
| Package renamed                                   |         |PMC               |
| Package tagged                                      |         |PMC               |

**Comment by AnthonyLaw** [comment]
Branch: https://github.com/nemfoundation/nem2-explorer/tree/rebranding
Preview: http://explorer-fo38ike3.nemtech.network/

**Comment by AnthonyLaw** [comment]
already merged into Master
