### ISSUE TITLE
Inner transaction "show detail"

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/symbol-explorer#381]
I think that it is not very obvious that the "show detail" button is clickable

Maybe a text-decoration:underline and a cursor: pointer would help?

Also, there is [object, Object] in the alt poptip

![image](https://user-images.githubusercontent.com/36499647/77870605-6be27f00-7274-11ea-8cf5-0043da399414.png)

**Comment by AnthonyLaw** [comment]
Thanks for feedback.
will take a look on this.
