### ISSUE TITLE
Some "Transfer" transactions don't transfer anything so are they really Transfer Transactions?  

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/symbol-explorer#417]
For example. This transaction http://explorer.symboldev.network/transaction/5445FE00F77AF111D187E7BFE0BD5AECB6FE9EFDF84C08427A1254C9344E4D2F from looking at the block explorer it is called a "transfer" transaction but I can't seem to see any mosaic being transferred, but instead, only a message was sent. 

So I'm wondering if we shouldn't call it "Message transaction". I know on the backend that is not the developer speak but from the end-user perspective calling a message transaction a transfer transaction is a bit misleading. 

There is another case to where an empty transaction is sent and there is no message and no mosaics being sent. In that case, I think it might be nice to be labeled "empty transaction" so people don't get confused.

**Comment by AnthonyLaw** [comment]
The "transfer" transaction is follow the network transaction type.
Our document show message under transfer transaction.

https://nemtech.github.io/concepts/transfer-transaction.html#message

In my opinion, should follow with documentation.

**Comment by OlegMakarenko** [comment]
I agree with Anthony that it can be better to follow the docs. So there will not be misunderstanding that user announced `Transfer` transaction but in the explorer it is shown as a `MessageTransaction`. I think it may have more sense to show some user-friendly transaction types in the wallet rather in the explorer which i think more developer oriented and in this perspective the data is shown here should be accurate. 

We can simply add `note` field to the **Transaction Info** table which can provide a clarification comment.

What do you think?
@jabo38 @AnthonyLaw  @evias

**Comment by jabo38** [comment]
There is no perfect solution because we have a transaction type called “transfer transaction” in which there is no transfer. But it’s still and “transfer transaction” technically so I get why we want to look at it and call it that. At the same time, I personally think we should be building tools for users so it’s something to think about. 

Take for instance this Tx, there is no transfer and no message. That had to be totally confusing to a regular user browsing the explorer. 

http://explorer.symboldev.network/transaction/9D6731381F17CB7D27C6760FBE2F38927F8B228EA86A17CB2F67C2455D1ACCEA

This could at least in part be mitigated by being more clear and spelling it out with fields “message: no message” and “mosaic transfer: no mosaic transferred”. Or something along those lines. By doing this newbies won’t be confused.

**Comment by AnthonyLaw** [comment]
![image](https://user-images.githubusercontent.com/5649156/80800815-0ec44b00-8bdd-11ea-8956-3347304446a5.png)

how about this?
@jabo38 @OlegMakarenko @evias 

If the Tx is only Message
   it will show like the photo above.

else remain the the same.

**Comment by OlegMakarenko** [comment]
@jabo38 @AnthonyLaw I think `Remark` field from Anthony and `Transaction Graphic` solved this issue. Can we close it, or any other ideas?

**Comment by AnthonyLaw** [comment]
yeah, i think we can close this.
