### ISSUE TITLE
Create config for the e2e tests

### ISSUE THREAD

**Issue by OlegMakarenko** [nemfoundation/symbol-explorer#419]
Move hard-coded data from *.spec.js to config such as:
- Native mosaicId
- Account address 
- transactionHash
etc

**Comment by AnthonyLaw** [comment]
Rather than move to config.
I will add Fixture file for test.
what you think?
https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Fixture-Files

**Comment by OlegMakarenko** [comment]
@AnthonyLaw I'm not sure about Fixture file. Can be just to read `config/network.conf` or `config/network.json` before the test

**Comment by AnthonyLaw** [comment]
@OlegMakarenko yeah, that is most simple solution. 
but i think i will create `e2e/config/network.conf` 👍
