### ISSUE TITLE
[Bug] Failed to fetch account detail - TooManyRequests

### ISSUE THREAD

**Issue by OlegMakarenko** [nemfoundation/symbol-explorer#438]
![image](https://user-images.githubusercontent.com/33131259/81214332-60efdc80-8fe0-11ea-85e2-d6ae4735d680.png)
**route:**
/account/TATGZXFW3OTHPZT4G4IVDD2K7PXIJJXGEVCKP72W

```
Error: {
 "statusCode":429,
 "errorDetails": {
   "statusCode":429,
   "statusMessage":"Too Many Requests"
 },
 "body": {
  "code":"TooManyRequests",
  "message":"You have exceeded your request rate of 7 r/s."
 }
}
```

**Comment by AnthonyLaw** [comment]
@OlegMakarenko 
can you try on this endpont

`api-01.eu-central-1.0941-v1.symboldev.network`

**Comment by AnthonyLaw** [comment]
I have this issue with only this address, other address seem ok, maybe because the data request is less.

Error message
```
"body": {
  "code":"TooManyRequests",
  "message":"You have exceeded your request rate of 7 r/s."
 }
```
 
route: `/account/TATGZXFW3OTHPZT4G4IVDD2K7PXIJJXGEVCKP72W`

in endpont : 

```shell
api-t172-01.us-west-1.0941-v1.symboldev.network - new endpoint

api-01.ap-northeast-1.0941-v1.symboldev.network - old endpoint
api-02.ap-northeast-1.0941-v1.symboldev.network - old endpoint 
```

Only working endpoint
- api-01.eu-central-1.0941-v1.symboldev.network

**Comment by evias** [comment]
i also found out that after page load, if you **switch the node**, it will actually load all the components (also if it broke during page load)
