### ISSUE TITLE
Statistic page doesn't work

### ISSUE THREAD

**Issue by OlegMakarenko** [nemfoundation/symbol-explorer#443]
http://explorer-fo38ike3.symboldev.network/statistics

```
Access to fetch at 'http://api-01.us-west-1.symboldev.network:3000/network/fees/transaction' from origin 'http://explorer-fo38ike3.symboldev.network' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by AnthonyLaw** [comment]
This endpoint `http://api-01.us-west-1.symboldev.network:3000/network/fees/transaction`
should already outdated.

We should use the 941 version IMO
Endpoint : http://api-01.eu-west-1.0941-v1.symboldev.network:3000/network/fees/transaction
Explorer: http://explorer-941.symboldev.network/
