### ISSUE TITLE
Adding Russian translation

### ISSUE THREAD

**Issue by klimgeran** [nemfoundation/symbol-explorer#448]
I will add Russian translation for symbol-explorer

**Comment by AnthonyLaw** [comment]
sure thing 👍 

1. create an json name `ru.json` inside [i18n folder ](https://github.com/nemfoundation/symbol-explorer/tree/master/src/config/i18n)

2. Copy source from here [en-us.json](https://github.com/nemfoundation/symbol-explorer/blob/master/src/config/i18n/en-us.json)

3. add a pointer to Russian translation file [here](https://github.com/nemfoundation/symbol-explorer/blob/cae73e10823416acf7d46f8074c83e6be637c777/src/config/i18n/index.js#L1)
example : `'Russian': require('./ru.json')`

let me know anything you are not clear :)

**Comment by klimgeran** [comment]
I got it, thanks Anthony!
