### ISSUE TITLE
Move Network config in http.

### ISSUE THREAD

**Issue by AnthonyLaw** [nemfoundation/symbol-explorer#464]
currently network config is hard coded in the setup.json.
it should able the read network config from `REST` and keep into `http`
when the page is init.

**Comment by OlegMakarenko** [comment]
I think it's already done, isn't it?

**Comment by AnthonyLaw** [comment]
https://github.com/nemfoundation/symbol-explorer/blob/be4984b60e1f984968c18817f61ae3c5cb36c9dc/src/config/setup.json.mt#L50

this one, it should request from `/network/properties`
