### ISSUE TITLE
Namespace table wording

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/symbol-explorer#467]
In the namespace table, it reads: Duration: in 10 months

It should say: Expiration: in 10 months
or: Duration: 10 months

"Approximate Expired" should be renamed to something like "Approximate expiration date"
I guess the problem is that we can't fill 3 words there, but "Approximate Expired" doesn't work on a grammar standpoint.
Maybe you can put "Expires at *"
and then at the bottom of the table, you put something like _* This date is approximative and for reference only_

![image](https://user-images.githubusercontent.com/36499647/82719593-abf73880-9cde-11ea-8828-e99130586292.png)

**Comment by AnthonyLaw** [comment]
![image](https://user-images.githubusercontent.com/5649156/82898558-1e407500-9f8c-11ea-9b97-f570a9fae01a.png)

![image](https://user-images.githubusercontent.com/5649156/82898653-429c5180-9f8c-11ea-954c-d496b513f434.png)

I think the first diagram have better look compare to the second one.

@decentraliser

**Comment by decentraliser** [comment]
The problem is that "Approximate date" can be confusing since its not
obvious that it is indeed the *expiration* date

I think "Expiration date" would be better
