### ISSUE TITLE
Allow searching a public key

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/symbol-explorer#469]
If you enter a public key in the search bar, it will be only considered as a transaction hash

I'd expect to be able to find an account using a public key in the searchbar

![image](https://user-images.githubusercontent.com/36499647/82721470-dd2c3480-9cef-11ea-9278-ecfeeb24d78a.png)

**Comment by AnthonyLaw** [comment]
yeah, because Account public key and Trasnction hash is same length.
so we priority on search transaction rather then account.

we may add the endpoint for `account/<publicKey>`
