### ISSUE TITLE
Add disable fields Array in config/detail-pages

### ISSUE THREAD

**Issue by AnthonyLaw** [nemfoundation/symbol-explorer#496]
add `disableFields` under detail-pages

currently we have `fields` under detail-pages to filter data for display.

but in transaction detail, we want show all the fields, but certain data we need to hide.

Example: 
![image](https://user-images.githubusercontent.com/5649156/84376168-3f06fc80-ac13-11ea-9c1a-b45d1a097026.png)

we just need `transactionDescriptor` rather than the transaction code for end-user.

what you guy think @evias @OlegMakarenko  ?

**Comment by OlegMakarenko** [comment]
@AnthonyLaw I think we need there a name (Transfer, etc.) with an icon of the transaction type

**Comment by AnthonyLaw** [comment]
After disussion with @OlegMakarenko we will just do the change in the TransactionType components.
