### ISSUE TITLE
Explorer failed to load with Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by fullcircle23** [nemfoundation/symbol-explorer#505]
Under certain conditions, Block Explorer may load in one browser but not in another. There may be other or additional conditions that trigger the failure but what I've experienced is these two scenarios:
- Explorer loads in Chrome but fails to load in Safari (version 13.1.1 on macOS 10.13.6).
- Explorer loads in Chrome instance that is signed in with Google account **_A_** but fails to load in another Chrome instance signed in with Google account **_B_** (or not signed in i.e. Guest or Incognito).

The errors in dev console respectively in the aforementioned scenarios:

_Safari_
**TypeError: undefined is not an object (evaluating 'e[t].call')**

<img width="369" alt="image" src="https://user-images.githubusercontent.com/33846962/85500005-4071f500-b615-11ea-992a-c629625c8c9a.png">

_Chrome_
**Uncaught TypeError: Cannot read property 'call' of undefined**
￼￼
<img width="539" alt="image" src="https://user-images.githubusercontent.com/33846962/85499869-00ab0d80-b615-11ea-88c1-d2e90ec635cd.png">

In both Safari and Chrome, the error occurs when executing the following module function at this line (bootstrap:89) in
`function __webpack_require__(moduleId)`:
```
    modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
```

It seems Webpack is trying to load the module when not all of it's required chunks have been loaded. 
Tracing further to line `app.8768f3ae.js:172`, this could be the preceding "chunk-vendors".

```
    o.push([0, "chunk-vendors"]), a()
})({
    0: function(e, t, a) {
        e.exports = a("56d7")         <-- app.8768f3ae.js:172
    },
```

This may be related to webpack issue discussed in (https://github.com/webpack/webpack/issues/8996). One of the possible causes was that the default production deployment setting for `optimization.namedChunks` was `false` and the fix was to set it to `true`. 

The issue may also be caused by how dynamic imports are implemented in explorer code.

**Comment by AnthonyLaw** [comment]
@OlegMakarenko can you try it on your end?
my machine is working well.

**Comment by OlegMakarenko** [comment]
I cannot reproduce this bug
