### ISSUE TITLE
Use the explorer with private catapult node

### ISSUE THREAD

**Issue by BIMTrazer** [nemfoundation/symbol-explorer#507]
Greetings.

We would like to know if you can use this explorer on a private catapult (0.9.4.1) server.

We setup the node url on the file specified on the readme and it shows correct chain height but everything else show errors like "Unable to fetch data" or "Failed to fetch transaction list"

We were using project "catapult-block-explorer" here on github but that project is now inactive since several months ago, do you know if there is an alternative to this?

Thank you.

**Comment by AnthonyLaw** [comment]
Hi there, current master branch are support with catapult (0.9.5.1) server.

you can try on this branch https://github.com/nemfoundation/symbol-explorer/tree/0.9.4.1

**Comment by BIMTrazer** [comment]
Thank you.
I can see Blocks now, however the rest of the tabs show "Unable to fetch data", am I missing something with the config here? I can see that the networkConfig parameters have the same values as the server.

**Comment by AnthonyLaw** [comment]
The rest of the tabs `Unable to fetch data` I believe your api endpoint (rest) are not support those listing endpoint.
You can check open dev console in your browser, and check on the `network` tabs.

For the original `catapult-rest` are not support all listing other than Blocks.
So you may need the custom `catapult-rest`, check this out https://github.com/kaiyzen/catapult-rest

**Comment by BIMTrazer** [comment]
You're right! I was using original catapult-rest, with kaiyzen custom one I can now see "Transactions" and "Mosaics"

Thank you!

**Comment by AnthonyLaw** [comment]
I believe in next release, those custom endpoint will add into original catapult-rest. 👍
