### ISSUE TITLE
Internal `Transaction ID` is being treated and displayed as an entity attribute 

### ISSUE THREAD

**Issue by Vektrat** [nemfoundation/symbol-explorer#549]
We put a lot of insistence to this specific matter, and @martinayora just noticed that it is being disregarded anyway in this client (this is also the reason why the ID is out of the transaction context in the json object, unsure how SDK is handling/forwarding this).

`Transaction ID` is an internal attribute extremely dependent on the database layer that should die at the step where pagination is managed, yet it is being clearly brought to the user's eyes - giving the false impression of it being the transaction id, where in reality this concept does not exist - it is a database-transaction-entity-id (ObjectId), which has no place in the client domain.

For these reasons, and due to the distributed nature of the project, the ID of a transaction will change among different nodes, even for the same transaction, and cannot be trusted as a fixed reference for this object.

We believe this concept should be completely removed from the interface, or it will cause obvious confusion.

![image](https://user-images.githubusercontent.com/434196/88036250-95852600-cb43-11ea-8baa-d0a4c4b1cde7.png)

**Comment by OlegMakarenko** [comment]
Thanks @Vektrat , we will fix it
